#-*- encoding:utf-8 -*-#

EC_REGISTER_PHONE_TYPE_ERROR=101
ER_REGISTER_PHONE_TYPE_ERROR='手机号格式错误'

EC_REGISTER_USERID_REPEAT=102
ER_REGISTER_USERID_REPEAT='账号重复'

EC_REGISTER_IDCARD_TYPE_ERROR=103
ER_REGISTER_IDCARD_TYPE_ERROR='身份证号格式错误'

EC_REGISTER_PASSWORD_TYPE_ERROR=104
ER_REGISTER_PASSWORD_TYPE_ERROR='密码格式错误'

EC_LOGIN_USERID_ERROR=201
ER_LOGIN_USERID_ERROR='账号错误'

EC_LOGIN_PASSWORD_ERROR=202
ER_LOGIN_PASSWORD_ERROR='密码错误'